name: pipeline

on:
  push:
    branches:
      - 'master'
      - 'release/**'

env:
  image_name: rcb

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.set_version.outputs.safe_version }}
    steps:
      -
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Set application version
        id: set_version
        uses: kvendingoldo/semver-action@v1.11
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build docker image and push it
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            kvendingoldo/${{ env.image_name }}:latest
            kvendingoldo/${{ env.image_name }}:${{ steps.set_version.outputs.safe_version }}
      -
        name: Print image version
        run: echo ${{ steps.set_version.outputs.safe_version }}
